- name: 'Get secrets'
  id: azure-keyvault-secrets
  run: |
    secrets_get=(example1 example2)
    for secret_get in ${secrets_get[@]}
    do
      value=$(az keyvault secret show --name $secret_get --vault-name testSC --query value --output tsv)
      echo "::add-mask::$value"
      echo "$secret_get=$value" >> $GITHUB_OUTPUT
    done
